# Generated by Django 3.2.5 on 2021-08-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='pic_folder/')),
                ('is_like', models.BooleanField(null=True)),
            ],
        ),
    ]
