# Generated by Django 3.2.5 on 2021-08-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
