# Generated by Django 3.2.5 on 2021-08-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_eventdetails_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='time',
            field=models.TimeField(),
        ),
    ]
